# Generated by Django 2.0.7 on 2018-07-18 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='프로젝트 이름')),
                ('description', models.TextField(blank=True, verbose_name='프로젝트 설명')),
                ('secure_level', models.PositiveIntegerField(choices=[(1, '모두 참여 가능'), (2, '팀원 지정'), (3, '개인')], verbose_name='공개범위')),
                ('published_date', models.DateField(editable=False)),
                ('directors', models.ManyToManyField(blank=True, related_name='project_directors', to=settings.AUTH_USER_MODEL, verbose_name='팀원')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to=settings.AUTH_USER_MODEL, verbose_name='총괄 디렉터')),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Information'),
        ),
    ]
