# Generated by Django 2.0.7 on 2018-07-18 22:44

import django.core.validators
from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_information_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='file',
            field=models.FileField(blank=True, upload_to=projects.models.custom_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='기획서'),
        ),
    ]
