# Generated by Django 2.0.7 on 2018-07-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180719_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='secure_level',
            field=models.PositiveIntegerField(choices=[(1, '모두 참여 가능'), (2, '팀원 지정'), (3, '개인 진행')], verbose_name='공개 범위'),
        ),
    ]
